some changes to pg.sql file

diff --git a/.github/workflows/csn-devsecops-wf.yml b/.github/workflows/csn-devsecops-wf.yml
--- a/.github/workflows/csn-devsecops-wf.yml
+++ b/.github/workflows/csn-devsecops-wf.yml
@@ -1,17 +1,17 @@
 name: csn-devsecops-wf
 
 on:
-   workflow_dispatch:
+  workflow_dispatch:
     inputs:
       devsecops_action:
         type: choice
         description: Select DevSecOps Action
         options:
-        - btpscani
-        - deploy
-        - dast
+          - btpscani
+          - deploy
+          - dast
         required: true
-   
+
 permissions:
   checks: write
 
@@ -25,78 +25,79 @@ jobs:
 
       - name: SAST Scan
         run: grep -r -e "password" -e "secret" -e "keys" .
-      
+
       # Install Docker Compose
       - name: Install Docker Compose
         run: |
           sudo apt-get update
           sudo apt-get install -y docker-compose
-      
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-  
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build the Docker images
-        run: |
-          docker-compose --file=docker-compose.local.yml up -d
-          docker-compose --file=docker-compose.local.yml up -d --build
+      - name: Build and start Docker containers
+        run: docker-compose --file=docker-compose.local.yml up -d --build
 
-      - name: Checking for images built and pulled 
+      - name: Checking for images built and pulled
         run: sudo docker images
 
       # Tagging the Docker images manually using docker tag command
       - name: Tag Docker images
         run: |
-          docker tag brokencrystals_nodejs:latest ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:nodejs-${{ github.sha }}
-          docker tag postgres:latest ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:postgres-${{ github.sha }}
-          docker tag sj26/mailcatcher:latest ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:mailcatcher-${{ github.sha }}
-                
+          docker tag brokencrystals_nodejs:latest ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:nodejs-${{ github.sha }}-${{ github.ref_name }}
+          docker tag postgres:latest ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:postgres-${{ github.sha }}-${{ github.ref_name }}
+          docker tag sj26/mailcatcher:latest ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:mailcatcher-${{ github.sha }}-${{ github.ref_name }}
+
       - name: Push Docker images
         run: |
-          docker push ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:nodejs-${{ github.sha }}
-          docker push ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:postgres-${{ github.sha }}
-          docker push ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:mailcatcher-${{ github.sha }}
-          
+          docker push ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:nodejs-${{ github.sha }}-${{ github.ref_name }}
+          docker push ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:postgres-${{ github.sha }}-${{ github.ref_name }}
+          docker push ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:mailcatcher-${{ github.sha }}-${{ github.ref_name }}
 
   deploy:
     runs-on: ubuntu-latest
-    # needs: sast
+    #needs: btpscani  # Ensure that deploy job depends on successful completion of btpscani job
     if: ${{ github.event.inputs.devsecops_action == 'deploy' }}
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-east-1 
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
 
-    - name: Set up Kubectl
-      uses: azure/setup-kubectl@v1
+      - name: Set up Kubectl
+        uses: azure/setup-kubectl@v1
 
-    - name: Load AWS EKS credentials
-      run: aws eks update-kubeconfig --name cloudsec_cluster  --region us-east-1 # Change to your cluster name
-  
-    - name: Update Deployment Image 
-      # env:
-      #    IMAGE_TAG: ${{ github.sha }}
-         
-      run: |
-        sed -i "s/VERSION_TAG/${{ github.sha }}/g" ./k8s/app.yaml
-       
-    - name: Deploy to EKS
-      run: kubectl apply -f k8s/  --validate=false # Path to your Kubernetes config files
-  
-    - name: Verify deployment
-      run: kubectl rollout status deployment/nodejs # Change to your deployment resource name
+      - name: Load AWS EKS credentials
+        run: aws eks update-kubeconfig --name cloudsec_cluster --region us-east-1 # Change to your cluster name
 
+      - name: Update Deployment Image
+        run: |
+          sed -i "s/VERSION_TAG/${{ github.sha }}/g" ./k8s/app.yaml
+
+      - name: Deploy to EKS
+        run: kubectl apply -f k8s/ --validate=false # Path to your Kubernetes config files
+
+      - name: Verify deployment and check application health
+        run: |          
+          kubectl rollout status deployment/nodejs-deployment --timeout=5m || { echo 'Deployment Verification failed'; exit 1; } # Verify the deployment rollout status
+
+          # Wait for the pods to be running and ready
+          kubectl wait --for=condition=ready pod -l app=nodejs-deployment --timeout=5m || { echo 'Pod readiness check failed'; exit 1; }
+
+          # Optional: Perform a simple health check by hitting the application's endpoint
+          # Replace <your-app-url> with the actual URL for your application
+          curl --fail --silent --show-error http://<your-app-url>/health || { echo 'Health check failed'; exit 1; }
 
   dast:
     runs-on: ubuntu-latest
@@ -105,4 +106,4 @@ jobs:
       - name: OWASP ZAP DAST Scan
         continue-on-error: true
         run: |
-          docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t 'https://kattafuah.github.io/brokencrystals/' || true
+          docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t 'https://kattafuah.github.io/brokencrystals/' -r zap-report.html || true
