modified deploy job in wf file

diff --git a/.github/workflows/csn-devsecops-wf.yml b/.github/workflows/csn-devsecops-wf.yml
--- a/.github/workflows/csn-devsecops-wf.yml
+++ b/.github/workflows/csn-devsecops-wf.yml
@@ -92,10 +92,10 @@ jobs:
         run: |          
           kubectl rollout status deployment/nodejs-deployment --timeout=5m || { echo 'Deployment Verification failed'; exit 1; }
 
-          kubectl wait --for=condition=ready pod -l app=nodejs-deployment --timeout=5m || { echo 'Pod readiness check failed'; exit 1; }
+          kubectl wait --for=condition=ready pod -l app=nodejs --timeout=5m || { echo 'Pod readiness check failed'; exit 1; }
 
           # Fetch the application URL from the ingress or service
-          APP_URL=$(kubectl get svc nodejs-deployment -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+          APP_URL=$(kubectl get svc nodejs-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
           echo "Application URL is: $APP_URL"
 
           # Set the URL as an output to be used in the next job
